-- I used the solution in https://github.com/Sheinxy/Advent-Of-Code/blob/main/2023/Day_20/Day_20.hs
-- and I still want to properly understand and annotate it, before I build upon it to make my own.
-- TBD.